workflow:
    name: "MERN CI CD pipeline"
    rules: 
        - if: $CI_COMMIT_BRANCH== 'main' || $CI_COMMIT_BRANCH=~ /^feature/
          when: always
stages:
    - test
    - build
    - provision
    - deploy


testing:
  stage: test
  image: node:17-alpine3.14
  services:
     - name: mongo
       alias: mongodb

  artifacts:
    when: always          # ← save report even if tests fail
    reports:
      junit: TODO/todo_backend/reports/junit.xml  # ← GitLab reads this
    expire_in: 1 week    

  cache:
     policy: pull-push
     when: on_success
     key:
        files:
          - /TODO/todo-backend/package.son
     paths:
        - /TODO/todo-backend/node_modules
  before_script:
   - cd TODO/todo_backend
   - npm install
   - npm install jest-junit
  script:
     - npm test
     - echo "=== XML content ==="
     - cat reports/junit.xml
    

build:
  stage: build
  image: docker:24
  services:
    - name: docker:24-dind
      alias: docker
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin
  script:
    # ── Backend ──
    - docker build -f docker/dockerfile.backend -t $DOCKERHUB_USERNAME/todo-backend:latest .
    - docker push $DOCKERHUB_USERNAME/todo-backend:latest

    # ── Frontend ──
    - docker build -f docker/dockerfile.frontend -t $DOCKERHUB_USERNAME/todo-frontend:latest .
    - docker push $DOCKERHUB_USERNAME/todo-frontend:latest

  needs:
    - job: testing
      artifacts: false
  rules:
    - if: $CI_COMMIT_BRANCH == "main"

terraform-provisioning:
  stage: provision
  image:
    name: hashicorp/terraform:1.6.0
    entrypoint:
      - ""
  before_script:
    - cd terraform
    - terraform init 
  script:
    - terraform validate
    - terraform plan -var="ssh_public_key=$EC2_SSH_PUBLIC_KEY"
    - terraform apply -auto-approve -var="ssh_public_key=$EC2_SSH_PUBLIC_KEY"

   
    - terraform output -raw ec2_public_ip > ../ec2_ip.txt
    - echo "EC2 deployed at → $(cat ../ec2_ip.txt)"   
  artifacts:
    paths:
      - ec2_ip.txt        # ← pass EC2 IP to deploy job
    expire_in: 1 hour  
  needs:
    - job: build  
  rules:
    - if: $CI_COMMIT_BRANCH == "main"  

deploying:
  stage: deploy
  image: alpine:latest

  before_script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$EC2_SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa

  script:
    - EC2_IP=$(cat ec2_ip.txt)
    - ssh-keyscan -H $EC2_IP >> ~/.ssh/known_hosts
    - scp docker-compose.prod.yml ec2-user@$EC2_IP:~/docker-compose.yml
    - |
      ssh ec2-user@$EC2_IP << EOF
        export MONGO_URI='$MONGO_URI'
        docker-compose pull
        docker-compose down
        docker-compose up -d
      EOF

  needs:
    - job: provision
      artifacts: true
  rules:
    - if: $CI_COMMIT_BRANCH == "main"



