workflow:
    name: "MERN CI CD pipeline"
    rules: 
        - if: $CI_COMMIT_BRANCH== 'main' || $CI_COMMIT_BRANCH=~ /^feature/
          when: always
stages:
    - test


testing:
  stage: test
  image: node:17-alpine3.14
  services:
     - name: mongo
       alias: mongodb

  artifacts:
    when: always          # ← save report even if tests fail
    reports:
      junit: TODO/todo_backend/reports/junit.xml  # ← GitLab reads this
    expire_in: 1 week    

  cache:
     policy: pull-push
     when: on_success
     key:
        files:
          - /TODO/todo-backend/package.son
     paths:
        - /TODO/todo-backend/node_modules
  before_script:
   - cd TODO/todo_backend
   - npm install
   - npm install jest-junit
  script:
     - npm test
     - echo "=== XML content ==="
     - cat reports/junit.xml
    
