# Stage 2: Build the React app
FROM node:20-alpine AS build

WORKDIR /app
COPY ../TODO/todo_frontend/package*.json .
RUN npm install
COPY ../TODO/todo_frontend/ .
RUN npm run build

# Stage 2: 
FROM nginx:alpine

RUN rm -rf /usr/share/nginx/html/*

COPY --from=build /app/build /usr/share/nginx/html

COPY ../TODO/nginx/default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]