services:
  backend:
    build:
      context: ..   # ← go UP then into TODO
      dockerfile: /docker/dockerfile.backend
    container_name: todo_backend
    ports:
      - "5000:5000"
    env_file:
      - ../TODO/todo_backend/.env
    networks:
      - todo_network

  nginx:
    build:
      context: ..   # ← go UP then into TODO
      dockerfile: /docker/dockerfile.frontend
    container_name: todo_frontend
    ports:
      - "80:80"
    networks:
      - todo_network

networks:
  todo_network:
    driver: bridge